# Use the official lightweight Python image.
FROM python:3.9-slim

ENV PYTHONUNBUFFERED True

WORKDIR /app

COPY pyproject.toml .
RUN pip install --no-cache-dir .

# Copy everything, then we just run uvicorn
COPY . .

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
