/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata */
        get: operations["metadata_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimize */
        post: operations["optimize_v1_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_v1_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AffectPoint */
        AffectPoint: {
            /** Arousal */
            arousal: number;
            /** Valence */
            valence: number;
        };
        /**
         * DayNight
         * @enum {string}
         */
        DayNight: "Day" | "Night";
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[] | null;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Model Status */
            model_status: string;
            /** Ready */
            ready: boolean;
            /** Reason */
            reason?: string | null;
            /** Schema Version */
            schema_version: string;
            /**
             * Status
             * @constant
             */
            status: "alive";
        };
        /** MetaResponse */
        MetaResponse: {
            /** Artifact Version */
            artifact_version: string | null;
            /** Data Manifest Sha256 */
            data_manifest_sha256: string;
            /** Limitations */
            limitations: string[];
            /** Model Status */
            model_status: string;
            /** Ready */
            ready: boolean;
            /** Schema Version */
            schema_version: string;
        };
        /** OptimizeCandidate */
        OptimizeCandidate: {
            prediction: components["schemas"]["PredictionPayload"];
            room: components["schemas"]["RoomInput"];
            support: components["schemas"]["SupportPayload"];
        };
        /** OptimizeRequest */
        OptimizeRequest: {
            /**
             * Budget
             * @default 500
             */
            budget: number;
            day_or_night?: components["schemas"]["DayNight"] | null;
            /**
             * N Candidates
             * @default 5
             */
            n_candidates: number;
            /**
             * Seed
             * @default 2718
             */
            seed: number;
            space_type?: components["schemas"]["SpaceType"] | null;
            target: components["schemas"]["AffectPoint"];
        };
        /** OptimizeResponse */
        OptimizeResponse: {
            /** Candidates */
            candidates: components["schemas"]["OptimizeCandidate"][];
            /** Limitations */
            limitations: string[];
            /** Model Status */
            model_status: string;
            /** Reason */
            reason: string | null;
            /** Samples Evaluated */
            samples_evaluated: number;
            /** Schema Version */
            schema_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "empty";
        };
        /** PredictRequest */
        PredictRequest: {
            room: components["schemas"]["RoomInput"];
            target: components["schemas"]["AffectPoint"];
        };
        /** PredictResponse */
        PredictResponse: {
            /** Limitations */
            limitations: string[];
            /** Model Status */
            model_status: string;
            prediction: components["schemas"]["PredictionPayload"];
            /** Schema Version */
            schema_version: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
            support: components["schemas"]["SupportPayload"];
        };
        /** PredictionPayload */
        PredictionPayload: {
            /** Arousal */
            arousal: number;
            /** Neuro Score */
            neuro_score: number;
            /** Projected */
            projected: boolean;
            /** Raw Arousal */
            raw_arousal: number;
            /** Raw Valence */
            raw_valence: number;
            /** Valence */
            valence: number;
        };
        /**
         * RoomInput
         * @description Independent variables only; missing optional observations are not zeros.
         */
        RoomInput: {
            /** Cct */
            cct?: number | null;
            day_or_night?: components["schemas"]["DayNight"] | null;
            /** Daylight Factor */
            daylight_factor?: number | null;
            /** Door Area */
            door_area?: number | null;
            /** Height */
            height: number;
            /** Illuminance */
            illuminance?: number | null;
            /** Length */
            length: number;
            /** Num Doors */
            num_doors?: number | null;
            /** Num Windows */
            num_windows?: number | null;
            space_type?: components["schemas"]["SpaceType"] | null;
            /** Walkable Floor Area */
            walkable_floor_area?: number | null;
            /** Width */
            width: number;
            /** Window Area */
            window_area?: number | null;
        };
        /**
         * SpaceType
         * @enum {string}
         */
        SpaceType: "General" | "Bedroom" | "Living Room" | "Workplace" | "Classroom" | "Cafeteria";
        /** SupportPayload */
        SupportPayload: {
            /** Nearest Room Id */
            nearest_room_id: string | null;
            /** Reason */
            reason?: string | null;
            /** Standardized Distance */
            standardized_distance: number | null;
            /** Status */
            status: string;
            /** Threshold */
            threshold: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metadata_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    optimize_v1_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizeResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    predict_v1_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
