import { useState } from 'react';
import { useResearch } from '../lib/research';
import Circumplex, { type AffectPoint } from '../figures/Circumplex';
import Sensitivity from '../figures/Sensitivity';
import { Notice, PageHeading, Section, Value } from '../ui';

export default function Affect() {
  const state = useResearch(); const data = state.status === 'ready' ? state.data : null;
  const [experiment, setExperiment] = useState('all'); const [person, setPerson] = useState('all'); const [component, setComponent] = useState<'subjective' | 'objective' | 'fused'>('fused'); const [alpha, setAlpha] = useState('all');
  const trials = data?.trials.filter(row => (experiment === 'all' || String(row.experiment) === experiment) && (person === 'all' || row.participant_id === person)) || [];
  const complete = trials.filter(trial => trial.cohort === 'complete_fusion' && trial.fused);
  const partial = trials.filter(trial => trial.cohort === 'partial_modality_fusion' && trial.fused);
  const points: AffectPoint[] = trials.flatMap(trial => { const position = trial[component]; return position ? [{ id: trial.id, label: `${trial.participant_id}, ${trial.room_id}`, position, kind: component, cohort: trial.cohort, cct: data?.rooms.find(room => room.id === trial.room_id)?.cct_kelvin }] : []; });
  const people = [...new Set(data?.trials.map(trial => trial.participant_id) || [])].sort();
  const alphaValues = [...new Set(data?.sensitivity.map(row => row.alpha) || [])].sort((a, b) => a - b);
  const sensitivity = data?.sensitivity.filter(row => (experiment === 'all' || String(row.experiment) === experiment) && (alpha === 'all' || String(row.alpha) === alpha)) || [];
  return <><PageHeading eyebrow="Descriptive synthesis" title="Affect" intro="Compare self-report, physiology-based and fused positions without treating their common coordinate system as proof that they measure the same construct." />
    {!data ? <Notice title="Affect export unavailable" warning><p>{state.status === 'error' ? state.message : 'Loading validated positions.'}</p></Notice> : <><div className="toolbar"><label>Experiment<select value={experiment} onChange={event => setExperiment(event.target.value)}><option value="all">All experiments</option>{data.study.experiments.map(item => <option key={item.id} value={item.id}>Experiment {item.id}</option>)}</select></label><label>Participant<select value={person} onChange={event => setPerson(event.target.value)}><option value="all">All participant IDs</option>{people.map(item => <option key={item}>{item}</option>)}</select></label><label>Component<select value={component} onChange={event => setComponent(event.target.value as typeof component)}><option value="fused">Fused</option><option value="subjective">Self-report</option><option value="objective">Physiology mapped</option></select></label><label>Sensitivity α<select value={alpha} onChange={event => setAlpha(event.target.value)}><option value="all">All exported weights</option>{alphaValues.map(value => <option key={value} value={value}>{value}</option>)}</select></label><span className="status">{component === 'fused' ? `${complete.length} complete + ${partial.length} partial-modality fused positions` : `${points.length} ${component} positions`} from {trials.length} {trials.length === 1 ? 'trial' : 'trials'}</span></div>
      <div className="page-grid"><div className="reading"><Section title="What is combined"><p>The subjective component uses eligible self-report. The objective component maps eligible physiology to proposed coordinates. The fused component combines available eligible pairs using the documented weight α. A trial with one missing component is not silently promoted to complete fusion.</p><p>The plot changes component without moving an unavailable trial to an invented origin. Sample sizes can differ across these views.</p></Section>
        <Section title="Component availability"><div className="metric-row">{(['subjective', 'objective'] as const).map(key => <div className="metric-card" key={key}><span className="value">{trials.filter(trial => trial[key]).length}</span><span className="label">{key} positions</span></div>)}<div className="metric-card"><span className="value">{complete.length}</span><span className="label">Complete fusion</span></div><div className="metric-card"><span className="value">{partial.length}</span><span className="label">Partial-modality fusion</span></div></div></Section>
        <Section title="Independent people behind the positions"><p>{new Set(complete.map(trial => trial.participant_id)).size} participant IDs contribute complete-fusion positions; {new Set(partial.map(trial => trial.participant_id)).size} contribute partial-modality positions in this filter. A concentration of eligible trials in one person does not establish a population response.</p></Section>
        <Section title="Eligible records"><div className="table-wrap"><table className="data-table"><thead><tr><th scope="col">Trial</th><th scope="col">Person</th><th scope="col">Room</th><th scope="col">Cohort</th><th scope="col">Components</th><th scope="col">Valence</th><th scope="col">Arousal</th><th scope="col">Default α</th></tr></thead><tbody>{trials.map(trial => <tr key={trial.id}><th scope="row">{trial.id}</th><td>{trial.participant_id}</td><td>{trial.room_id}</td><td>{trial.cohort || 'Unclassified'}</td><td>{trial.available_components?.join(', ') || 'Unavailable'}</td><td><Value value={trial[component]?.valence} /></td><td><Value value={trial[component]?.arousal} /></td><td><Value value={trial.alpha} /></td></tr>)}</tbody></table></div></Section></div>
        <div className="figure-column"><Circumplex points={points} caption={`${component} positions from eligible trial records at the exported default settings.${component === 'fused' ? ` ${complete.length} are complete and ${partial.length} use partial modalities in this filter.` : ''} The α control filters the sensitivity table below; it does not recompute individual trial positions. Missing coordinates remain unavailable in the table.`} /><Sensitivity rows={sensitivity} /></div></div></>}
  </>;
}
