import { Link } from 'react-router-dom';
import manifest from '../../../data/renders/manifest.json';

const room = (id: string) => manifest.rooms.find(asset => asset.id === id)?.preview || manifest.rooms[0].preview;

export default function Landing() {
  return <div className="landing">
    <section className="landing-hero"><div className="hero-copy"><p className="eyebrow">Architectural research · human and spatial metrics</p><p className="hero-kicker">Predictive Atmospheres</p><h1>What if space could be read through experience?</h1><p className="lead">Predictive Atmospheres asks how the physical character of a room relates to what people report feeling and to signals recorded from the body. The project links architectural attributes, forehead EEG, wrist ECG and self-report in a pilot study of rendered rooms, then tests whether those relationships can inform a design tool.</p><div className="actions"><Link className="action-link" to="/study">Explore the study <span aria-hidden="true">↗</span></Link><Link className="action-link secondary" to="/studio">Open Design Studio <span aria-hidden="true">↗</span></Link></div></div><div className="hero-image"><img src={room('Rm_018')} alt="Rendered architectural room from the original study" /><span>01 / Room as stimulus</span></div></section>
    <section className="landing-thesis"><div className="section-number">01 · The premise</div><div><h2>From static space to lived response</h2><p>Architects can describe geometry, light and intended use with precision, but an occupant's changing experience is harder to represent in the same design workflow. The thesis calls this gap the <em>static environment problem</em>. Predictive Atmospheres investigates a way to place human response beside spatial description, while keeping measured signals, reported feelings and constructed interpretations distinct.</p></div></section>
    <section className="question-band"><div><p className="eyebrow">Research question</p><h2>Can linked human and spatial metrics help describe experiences of architectural rooms and support an experimental design feedback loop?</h2></div><div><p className="eyebrow">Working hypothesis</p><p>If room form, lighting and function are recorded alongside quality-checked physiology and self-report, their relationships may reveal patterns that a spatial model can test. A fused valence–arousal position is one proposed representation; its usefulness must be evaluated against separate components and simple baselines.</p></div></section>
    <section className="experiment-story"><div className="section-heading"><div><p className="eyebrow">The study structure</p><h2>Three experiments, one linked method</h2></div><Link to="/study">Read the protocol ↗</Link></div><div className="experiment-strip"><article><img src={room('Rm_004')} alt="Rendered room used in the Form experiment" /><span>01 / Form</span><h3>Geometry and comfort</h3><p>Room geometry varies while viewers report comfort. Comfort remains its own measure.</p></article><article><img src={room('Rm_014')} alt="Rendered room used in the Lighting experiment" /><span>02 / Lighting</span><h3>Openings and light</h3><p>Room openings and supplied luminous attributes vary. Reported valence and arousal are considered alongside physiological features.</p></article><article><img src={room('Rm_024')} alt="Rendered room used in the Function experiment" /><span>03 / Function</span><h3>Use and experience</h3><p>Rendered space types vary. Ratings and body-derived features can be compared across repeated pilot experiences.</p></article></div><p className="method-thread">Room attributes and original renders link by room and trial ID to EEG, ECG and available reports. Eligibility is checked before comparison. The atlas separates physiology-derived, self-reported and fused coordinates to show both agreement and disagreement.</p></section>
    <section className="contribution"><div className="section-number">02 · Contribution</div><div><h2>A research record that can be questioned</h2><p>The work contributes a linked room–response dataset, a documented analysis path and an experimental Design Studio. The studio scores a proposed room's predicted fused position against a visitor's chosen emotional target and can search for a feasible configuration close to a requested numerical Neuro-Score. Its schematic geometry and studied-room references are identified as such; predictions are limited by the evaluated model.</p><div className="text-links"><Link to="/rooms">Explore rooms and experience ↗</Link><Link to="/body">Compare body and report ↗</Link><Link to="/prediction">Inspect prediction evidence ↗</Link></div></div></section>
    <section className="researcher"><img src="/images/researcher.webp" width="360" height="640" alt="Portrait of Manideep Mamidala" /><div><p className="eyebrow">Researcher context</p><h2>Manideep Mamidala</h2><p>Through Predictive Atmospheres, I investigate how architectural space relates to physiological responses and reported experience, developing a linked methodology for human–spatial metrics. My aim is to explore how these metrics can inform design through comparative analysis and proof-of-concept tools that score proposed rooms and suggest spatial configurations toward a chosen experiential target.</p><div className="text-links"><a href="mailto:manideepmamidala2@gmail.com">Email: manideepmamidala2@gmail.com ↗</a><a href="https://www.linkedin.com/in/manideepmamidala" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://blog.iaac.net/predictive-atmospheres/" target="_blank" rel="noreferrer">IAAC project article ↗</a></div></div></section>
  </div>;
}
