import { Link } from 'react-router-dom';
import { useResearch } from '../lib/research';
import { Notice, PageHeading, Section, Value, modelStatusLabel } from '../ui';

export default function ModelReport() {
  const state = useResearch(); const data = state.status === 'ready' ? state.data : null;
  return <><PageHeading eyebrow="Experimental modeling" title="Model report" intro="The predictor is evaluated against simple baselines on held-out rooms and participants where the data allow. These results describe a pilot demonstrator, not a validated design tool." />
    {!data ? <Notice title="Model report unavailable" warning><p>{state.status === 'error' ? state.message : 'Loading model evaluation.'}</p></Notice> : <div className="page-grid"><div className="reading"><Notice title={`Model status: ${modelStatusLabel(data.model.status)}`} warning={data.model.status !== 'ready'}><p>{data.model.explanation}</p>{data.model.status === 'not_better_than_baseline' && <p>This experimental predictor did not improve on the reported baseline under held-out evaluation.</p>}</Notice>
      <Section title="Evaluation"><p>Separate room and participant held-out results matter because a model can recognize familiar people or rooms without generalizing to new ones. Model targets are constructed inside training folds; the descriptive within-person normalization shown elsewhere cannot be reused to evaluate an uncalibrated new person. Metrics with no eligible folds or calibration remain unavailable.</p>{data.model.metrics.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th scope="col">Measure</th><th scope="col">Value</th><th scope="col">Interval</th><th scope="col">n</th><th scope="col">Group</th></tr></thead><tbody>{data.model.metrics.map((metric, i) => <tr key={`${metric.name}-${i}`}><th scope="row">{metric.name}</th><td><Value value={metric.value} unit={metric.unit || undefined} /></td><td>{metric.interval ? `${metric.interval[0].toFixed(2)}–${metric.interval[1].toFixed(2)}` : 'Unavailable'}</td><td><Value value={metric.n} /></td><td>{metric.group || '—'}</td></tr>)}</tbody></table></div> : <p>No eligible model metric is available.</p>}</Section>
      <Section title="Known limits">{data.model.limitations.length ? <ul>{data.model.limitations.map((item, i) => <li key={i}>{item}</li>)}</ul> : <p>See the versioned model card for data and method limits.</p>}<p>Explore the <Link to="/simulator">room simulator</Link> only with this status in mind. It surfaces unsupported or unavailable predictions rather than inventing intervals.</p></Section></div><div className="figure-column"><div className="card"><h3>Artifact and evidence</h3><p className="small-text">Artifact version: {data.model.artifact_version || 'Unavailable'}</p><p className="small-text">Schema version: {data.schema_version}</p><p className="small-text">Source: {data.provenance.source}</p><p className="small-text">Method: {data.provenance.method}</p></div></div></div>}
  </>;
}
