import { useState } from 'react';
import { useResearch } from '../lib/research';
import Circumplex from '../figures/Circumplex';
import { Notice, PageHeading, Section, Value } from '../ui';

export default function People() {
  const state = useResearch(); const data = state.status === 'ready' ? state.data : null;
  const [experiment, setExperiment] = useState('all'); const [person, setPerson] = useState('all');
  const people = data?.people.filter(row => (experiment === 'all' || row.experiments.includes(Number(experiment))) && (person === 'all' || row.id === person)) || [];
  const points = people.flatMap(row => row.mean_valence == null || row.mean_arousal == null ? [] : [{ id: row.id, label: row.id, position: { valence: row.mean_valence, arousal: row.mean_arousal } }]);
  return <><PageHeading eyebrow="Repeated experiences" title="People" intro="Participant IDs keep personal variation visible while respecting the data’s limits. Group patterns need independent units and adequate sample sizes; descriptive differences here are not causal effects." />
    {!data ? <Notice title="Participant export unavailable" warning><p>{state.status === 'error' ? state.message : 'Loading participant summaries.'}</p></Notice> : <><div className="toolbar"><label>Experiment<select value={experiment} onChange={event => setExperiment(event.target.value)}><option value="all">All experiments</option>{data.study.experiments.map(item => <option key={item.id} value={item.id}>Experiment {item.id}</option>)}</select></label><label>Participant<select value={person} onChange={event => setPerson(event.target.value)}><option value="all">All participant IDs</option>{data.people.map(row => <option key={row.id}>{row.id}</option>)}</select></label><span className="status">{people.length} participant summaries</span></div>
      <div className="page-grid"><div className="reading"><Section title="Participant summaries"><p>Means describe complete-fusion positions only; the count beside each person shows the records that contributed. A blank age, gender or sleep value was not measured or could not be safely mapped.</p><div className="table-wrap"><table className="data-table"><thead><tr><th scope="col">ID</th><th scope="col">Trials</th><th scope="col">Complete fusion n</th><th scope="col">Valence</th><th scope="col">Arousal</th><th scope="col">Age</th><th scope="col">Gender</th><th scope="col">Sleep</th></tr></thead><tbody>{people.map(row => <tr key={row.id}><th scope="row">{row.id}</th><td>{row.trials}</td><td>{row.valid_fused}</td><td><Value value={row.mean_valence} /></td><td><Value value={row.mean_arousal} /></td><td><Value value={row.age} /></td><td>{row.gender || 'Unavailable'}</td><td><Value value={row.sleep_hours} unit="h" /></td></tr>)}</tbody></table></div>{!people.length && <p>No participant matches this filter.</p>}</Section>
        <Section title="Interpreting cohort differences"><p>The experiments have different measured fields; sleep information is structurally absent outside the experiment that collected it. Repeated trials from one person are not independent participants. The atlas reports available descriptions without presenting a demographic effect when the export lacks defensible inference.</p></Section></div><div className="figure-column"><Circumplex points={points} caption="Per-participant mean of eligible fused positions. Each plotted person has a different number of contributing trials; table gives n. No uncertainty is inferred from point placement." /></div></div></>}
  </>;
}
