import { useState } from 'react';
import { useResearch, useSignalTrials } from '../lib/research';
import SignalTrace from '../figures/SignalTrace';
import { Empty, Notice, PageHeading, Section, Value } from '../ui';

export default function Signals() {
  const state = useResearch(); const data = state.status === 'ready' ? state.data : null;
  const signalState = useSignalTrials(data);
  const [experiment, setExperiment] = useState('all'); const [person, setPerson] = useState('all'); const [trialId, setTrialId] = useState(''); const [mode, setMode] = useState<'raw' | 'cleaned'>('raw');
  const inExperiment = (trial: { experiment: number }) => experiment === 'all' || String(trial.experiment) === experiment;
  const inScope = (trial: { experiment: number; participant_id: string }) => inExperiment(trial) && (person === 'all' || trial.participant_id === person);
  const people = [...new Set(data?.trials.filter(inExperiment).map(trial => trial.participant_id) || [])].sort();
  const trials = data?.trials.filter(inScope) || [];
  const signalTrials = signalState.status === 'ready' ? signalState.trials.filter(inScope) : trials;
  const active = signalTrials.find(trial => trial.id === trialId) || signalTrials[0];
  const unavailableEeg = trials.filter(trial => !trial.eeg_valid).length, unavailableRmssd = trials.filter(trial => !trial.ecg_valid).length;
  return <><PageHeading eyebrow="Physiological evidence" title="Signals and quality" intro="Inspect bounded signal traces beside the feature-eligibility decisions that shaped the analysis. Trace availability does not imply a valid derived feature; unavailable values are never replaced with nominal biometrics." />
    {!data ? <Notice title="Signal export unavailable" warning><p>{state.status === 'error' ? state.message : 'Loading validated trials.'}</p></Notice> : <>
      <div className="metric-row"><div className="metric-card"><span className="value">{trials.length}</span><span className="label">Trial records in filter</span></div><div className="metric-card"><span className="value">{unavailableEeg}</span><span className="label">EEG features unavailable</span></div><div className="metric-card"><span className="value">{unavailableRmssd}</span><span className="label">Primary RMSSD unavailable</span></div><div className="metric-card"><span className="value">{trials.filter(trial => trial.heart_rate_bpm != null).length}</span><span className="label">Heart-rate values</span></div><div className="metric-card"><span className="value">{trials.filter(trial => trial.rmssd_ms != null).length}</span><span className="label">RMSSD values</span></div></div>
      <div className="toolbar"><label>Experiment<select value={experiment} onChange={event => { setExperiment(event.target.value); setPerson('all'); setTrialId(''); }}><option value="all">All experiments</option>{data.study.experiments.map(row => <option key={row.id} value={row.id}>Experiment {row.id}</option>)}</select></label><label>Participant<select value={person} onChange={event => { setPerson(event.target.value); setTrialId(''); }}><option value="all">All participant IDs</option>{people.map(id => <option key={id} value={id}>{id}</option>)}</select></label><label>Trial<select value={active?.id || ''} onChange={event => setTrialId(event.target.value)}>{trials.map(trial => <option key={trial.id} value={trial.id}>{trial.id} · {trial.participant_id} · {trial.room_id}</option>)}</select></label><label>Trace<select value={mode} onChange={event => setMode(event.target.value as 'raw' | 'cleaned')}><option value="raw">Raw</option><option value="cleaned">Cleaned</option></select></label></div>
      {!active ? <Empty subject="Trial" /> : <div className="page-grid"><div className="reading"><Section title="Eligibility for this trial"><div className="metric-row"><div className="metric-card"><span className="value">{active.eeg_valid ? 'Available' : 'Unavailable'}</span><span className="label">EEG features</span></div><div className="metric-card"><span className="value">{active.ecg_valid ? 'Available' : 'Unavailable'}</span><span className="label">Primary RMSSD</span></div></div>{active.reasons.length ? <Notice title="Quality reasons" warning><ul>{active.reasons.map((reason, i) => <li key={i}>{reason}</li>)}</ul></Notice> : <p>No exclusion reason is recorded for this trial.</p>}
      <div className="table-wrap"><table className="data-table"><tbody><tr><th scope="row">Participant ID</th><td>{active.participant_id}</td></tr><tr><th scope="row">Room ID</th><td>{active.room_id}</td></tr><tr><th scope="row">Frontal asymmetry</th><td><Value value={active.faa} /></td></tr><tr><th scope="row">Heart rate</th><td><Value value={active.heart_rate_bpm} unit="bpm" /></td></tr><tr><th scope="row">RMSSD</th><td><Value value={active.rmssd_ms} unit="ms" /></td></tr></tbody></table></div></Section>
      <Section title="Band power">{active.eeg_band_power && Object.keys(active.eeg_band_power).length ? <div className="table-wrap"><table className="data-table"><thead><tr><th scope="col">Band</th><th scope="col">Exported power</th></tr></thead><tbody>{Object.entries(active.eeg_band_power).map(([band, value]) => <tr key={band}><th scope="row">{band}</th><td><Value value={value} /></td></tr>)}</tbody></table></div> : <p>No eligible band-power result was exported.</p>}</Section>
      <Section title="Interpretation"><p>EEG and wrist ECG are vulnerable to movement, contact and signal loss. Rejected regions are shaded in the plots; reasons and eligibility come from the backend quality protocol. The ECG flag denotes the stricter primary RMSSD feature, while heart rate has its own availability count. An available EEG feature passed stated checks; the recording is not guaranteed free of eye, muscle or movement artifact. The display does not diagnose affect from individual waves.</p></Section></div><div className="figure-column">{signalState.status === 'ready' ? <><SignalTrace title="EEG trace" trace={active.eeg} mode={mode} /><SignalTrace title="ECG trace" trace={active.ecg} mode={mode} /></> : <Notice title="Signal traces"><p>{signalState.status === 'error' ? signalState.message : 'Loading the separate signal trace product.'} Trial quality metadata remains available.</p></Notice>}</div></div>}
      <Section title="Trial quality table"><div className="table-wrap"><table className="data-table"><thead><tr><th scope="col">Trial</th><th scope="col">Person</th><th scope="col">Room</th><th scope="col">EEG features</th><th scope="col">Primary RMSSD</th><th scope="col">Heart rate</th><th scope="col">Reasons</th></tr></thead><tbody>{trials.map(trial => <tr key={trial.id}><th scope="row"><button className="subtle" onClick={() => setTrialId(trial.id)}>{trial.id}</button></th><td>{trial.participant_id}</td><td>{trial.room_id}</td><td>{trial.eeg_valid ? 'Available' : 'Unavailable'}</td><td>{trial.ecg_valid ? 'Available' : 'Unavailable'}</td><td>{trial.heart_rate_bpm != null ? 'Available' : 'Unavailable'}</td><td>{trial.reasons.join('; ') || '—'}</td></tr>)}</tbody></table></div></Section>
    </>}</>;
}
