import { Link } from 'react-router-dom';
import manifest from '../../../data/renders/manifest.json';
import { useResearch } from '../lib/research';
import Catalogue from './Catalogue';
import { Notice, PageHeading, Value } from '../ui';

export default function Study() {
  const state = useResearch();
  const data = state.status === 'ready' ? state.data : null;
  return <><PageHeading eyebrow="01 / Experimental framework" title="The Study" intro="How were architectural scenes, human signals and reported experiences brought into one research record? Three experiments vary Form, Lighting and Function across rendered rooms." />
    <div className="study-hero"><img src={manifest.rooms[6].preview} alt="A source render among the thirty rooms used as visual stimuli" /><div><span className="eyebrow">A linked room–response record</span><h2>One room can have many experiences.</h2><p>Participants viewed room renders while forehead EEG and wrist ECG were recorded. Ratings were available for the later experiments. Room IDs connect each exposure to its source render and supplied spatial attributes; trial IDs connect the response and quality decision.</p><Link to="/explore">Inspect the records ↗</Link></div></div>
    <div className="study-metrics" aria-label="Study scale">{data ? <><div><strong>{data.rooms.length}</strong><span>rendered rooms</span></div><div><strong>{data.trials.length}</strong><span>trial records</span></div><div><strong>{data.people.length}</strong><span>source participant IDs</span></div></> : <Notice title="Research counts loading"><p>{state.status === 'error' ? state.message : 'Reading the validated research export.'}</p></Notice>}</div>
    <section className="study-sequence"><div className="section-heading"><div><p className="eyebrow">Experimental design</p><h2>Form → Lighting → Function</h2></div><Link to="/rooms">View the rooms ↗</Link></div><div className="sequence-rows"><article><span>01</span><div><h3>Form</h3><p>Room geometry changes. The supplied response is comfort, kept separate from valence and arousal.</p></div><img src={manifest.rooms[2].preview} alt="Form experiment room render" /></article><article><span>02</span><div><h3>Lighting</h3><p>Opening and luminous attributes change. The study relates available reports to body-derived features while identifying uncalibrated environmental metadata.</p></div><img src={manifest.rooms[12].preview} alt="Lighting experiment room render" /></article><article><span>03</span><div><h3>Function</h3><p>Space types change. Repeated observations support comparisons within and across participants, with each denominator stated.</p></div><img src={manifest.rooms[22].preview} alt="Function experiment room render" /></article></div></section>
    <section className="linked-method"><div><p className="eyebrow">The measurement chain</p><h2>Keep each kind of evidence visible</h2></div><ol><li><strong>Room.</strong> Source geometry, type and supplied lighting values describe the rendered stimulus.</li><li><strong>Body.</strong> EEG and ECG features enter analysis only after the declared quality checks.</li><li><strong>Report.</strong> Comfort or valence–arousal responses retain their experiment-specific meaning.</li><li><strong>Interpretation.</strong> Physiology-derived and fused coordinates are constructed hypotheses, compared with reports and held-out model evidence.</li></ol></section>
    {data && <section className="experiment-table"><h2>Exposure structure</h2><div className="table-wrap"><table className="data-table"><caption>Exported experiment counts; participants and trials have different denominators.</caption><thead><tr><th scope="col">Experiment</th><th scope="col">Trials</th><th scope="col">People</th><th scope="col">Rooms</th><th scope="col">Recorded response</th></tr></thead><tbody>{data.study.experiments.map(item => <tr key={item.id}><th scope="row">{item.id}</th><td><Value value={item.trials} /></td><td><Value value={item.participants} /></td><td><Value value={item.rooms} /></td><td>{item.measured.join(', ') || 'Unavailable'}</td></tr>)}</tbody></table></div></section>}
    <Catalogue ids={['S1', 'S2', 'S3', 'S5']} title="Study structure and eligibility" />
  </>;
}
