import { Link } from 'react-router-dom';
import { useResearch, researchSource } from '../lib/research';
import Circumplex from '../figures/Circumplex';
import { Notice, PageHeading, Section } from '../ui';

export default function Study() {
  const state = useResearch();
  const data = state.status === 'ready' ? state.data : null;
  const complete = data?.trials.filter(trial => trial.cohort === 'complete_fusion' && trial.fused) || [];
  const partial = data?.trials.filter(trial => trial.cohort === 'partial_modality_fusion' && trial.fused) || [];
  const points = complete.map(trial => ({ id: trial.id, label: `${trial.participant_id}, ${trial.room_id}`, position: trial.fused!, kind: 'fused' as const, cohort: trial.cohort, cct: data?.rooms.find(room => room.id === trial.room_id)?.cct_kelvin }));
  return <><PageHeading eyebrow="Pilot research · Interactive atlas" title="How does a room feel in the body?" intro="Predictive Atmospheres studies how physiological signals and self-reported ratings describe the experience of rendered architectural spaces. The combined measure is a hypothesis to test, not a validated reading of emotion." />
    <div className="page-grid"><div className="reading">
      {data && <Section title="Abstract"><p>{data.study.abstract}</p></Section>}
      <Section title="The research question"><p>Can patterns in EEG and ECG, read alongside what a person reports, help describe their experience of a space? Participants viewed room renders in a headset. This atlas keeps the observations, assumptions and experimental predictions separate.</p><p>Move from <Link to="/rooms">rooms</Link> to <Link to="/signals">signal quality</Link>, then inspect the <Link to="/affect">component and fused positions</Link>. The <Link to="/model">model report</Link> explains whether architectural inputs predict held-out experiences.</p></Section>
      {data ? <Section title="Study at a glance"><div className="metric-row"><div className="metric-card"><span className="value">{data.study.experiments.length}</span><span className="label">Experiments in export</span></div><div className="metric-card"><span className="value">{data.rooms.length}</span><span className="label">Rooms with metadata</span></div><div className="metric-card"><span className="value">{data.trials.length}</span><span className="label">Trial records</span></div><div className="metric-card"><span className="value">{complete.length}</span><span className="label">Complete-fusion positions</span></div><div className="metric-card"><span className="value">{new Set(complete.map(trial => trial.participant_id)).size}</span><span className="label">People contributing complete fusion</span></div><div className="metric-card"><span className="value">{partial.length}</span><span className="label">Partial-modality fused positions</span></div></div><p className="small-text">Trial counts and independent people are different denominators. Complete and partial fusion are separate cohorts; the model uses a separate fold-fitted target procedure.</p><div className="table-wrap"><table className="data-table"><thead><tr><th scope="col">Experiment</th><th scope="col">Trials</th><th scope="col">People</th><th scope="col">Complete fusion / people</th><th scope="col">Partial fusion</th><th scope="col">Rooms</th></tr></thead><tbody>{data.study.experiments.map(row => { const ownComplete = complete.filter(trial => trial.experiment === row.id); return <tr key={row.id}><th scope="row">{row.id}</th><td>{row.trials}</td><td>{row.participants}</td><td>{ownComplete.length} / {new Set(ownComplete.map(trial => trial.participant_id)).size}</td><td>{partial.filter(trial => trial.experiment === row.id).length}</td><td>{row.rooms}</td></tr>; })}</tbody></table></div></Section> : <Notice title="Research results are being prepared" warning><p>{state.status === 'error' ? state.message : 'Loading the validated research export.'} The source renders remain available in Rooms.</p></Notice>}
      <Section title="How to read the experience"><p>Valence and arousal are coordinates for a proposed description. Subjective scores come from participants. Objective coordinates depend on documented physiological extraction and mapping assumptions. Fusion combines eligible components using an explicit weight; missing components remain missing.</p><p>The illustration shows only exported positions. It does not infer the start of a trial with no self-report.</p></Section>
      <Section title="Methods in brief"><p>Forehead EEG band power, asymmetry and wrist ECG intervals are quality checked before they contribute to a description. The source hardware rate and amplitude units are not fully established, so the rate scenario and accepted segments accompany each trace. The fused coordinate combines eligible mapped physiology and self-report under a documented weight α.</p><p>Neuro-Score is a bounded distance from a <em>user-selected</em> valence–arousal target: 1 − Euclidean distance / √8, clipped to [0, 1]. It describes target proximity under this coordinate model; it is not a health or design-quality score.</p></Section>
      <Section title="Protocol and limits">{data?.study.protocol.length ? <ol className="timeline">{data.study.protocol.map((step, i) => <li key={i}>{step}</li>)}</ol> : <p>Consult the protocol record for sequence and timing; no timing is inferred from a missing event log.</p>}{data?.study.limitations.length ? <ul>{data.study.limitations.map((item, i) => <li key={i}>{item}</li>)}</ul> : <p>This pilot has a small, repeated-measures sample and rendered stimuli. Environmental values were not calibrated against headset exposure, and associations are not causal effects.</p>}</Section>
      <Section title="Explore the evidence"><p><Link to="/people">People</Link> shows participant IDs and cohort summaries. <Link to="/simulator">Room simulator</Link> is an experimental demonstrator whose availability depends on model readiness. The original files, decisions and reproducible processing live in the repository.</p></Section>
      <Section title="Data and code"><p>Source recordings, source-derived participant IDs, room renders, processing code and generated results are organized in the <a href="https://github.com/manideepmamidala-sys/Predictive-Atmospheres_Mark-3" target="_blank" rel="noreferrer">project repository</a>. These IDs do not establish anonymization. A DOI or named biometric release is not asserted here. Consult the data and model cards before reusing outputs.</p></Section>
      {data && <p className="provenance">{researchSource(data)}</p>}
    </div><div className="figure-column"><Circumplex points={points} caption="Complete-fusion trial positions only. Partial-modality records are counted separately above and explored in Affect. No starting position is invented for missing self-report." /><p className="figure-note">The same plane appears across the atlas to make comparisons easier to read.</p></div></div></>;
}
